Hide menu
mojcacolnik/sea-of-choices pull request #38
Opened 2021-04-13 13:00 UTC by mojcacolnik

2021-04-13 13:16 UTC, mojcacolnik commented
Before I had the logout button at the bottom of the profile view, then when I implemented conditional rendering of buttons if user is logged in, I moved the logout button to the navbar. At the moment it is the only one not responding to the navbar collapsing at click, because it still has router.push action. Will keep working on it

2021-04-14 07:36 UTC, jkuri commented on frontend/src/App.vue
> +import axios from "axios";
why did you change single quotes to double quotes? please be consistent and use single quotes everywhere.

2021-04-14 07:40 UTC, jkuri commented on frontend/src/App.vue
> +    hideNavBar() {
I like this solution 👍

2021-04-14 07:41 UTC, jkuri requested changes
This solution works, but now I guess user does not have a option to log out since you removed it from Profile view, please fix that and then this PR is ready to be merged.

2021-04-14 19:13 UTC, merged